ShareDrive/ShareDrive/Areas/Admin/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using ShareDrive.Services.Contracts;
using ShareDrive.ViewModels.Admin.Car;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareDrive.Areas.Admin.Controllers
{
    public class CarsController : BaseController
    {
        private readonly ICarsService carsService;

        public CarsController(ICarsService carsService)
        {
            this.carsService = carsService;
        }

        public IActionResult Index()
        {
            IEnumerable<CarAdminIndexViewModel> cars = this.carsService.GetAllAdmin();
            return this.View("CarsIndex", cars);
        }
        
        [HttpGet]
        public IActionResult Details(int id)
        {
            var model = this.carsService.GetDetailsAdmin(id);
            return this.PartialView("_CarDetails", model);
        }
        

        [HttpPost]
        public IActionResult Delete(int id)
        {
            //bool result = this.carsService.Delete(id);
            bool result = true;

            if (result)
            {
                this.ViewData["SuccessMessage"] = "Car successfully deleted.";
            } 
            else
            {
                this.ViewData["ErrorMessage"] = "Cannot delete this car.";
            }
            
            IEnumerable<CarAdminIndexViewModel> cars = this.carsService.GetAllAdmin();
            return this.PartialView("_CarsIndexPartial", cars);
        }
    }
}

ShareDrive/ShareDrive/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using ShareDrive.Services.Contracts;
using ShareDrive.ViewModels.Admin.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareDrive.Areas.Admin.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult Index()
        {
            IEnumerable<ShareDrive.ViewModels.Admin.User.UserAdminIndexViewModel> users = this.usersService.GetAllAdmin();
            return this.View(users);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            UserAdminDetailsViewModel model = this.usersService.GetDetailsModel(id);
            return this.PartialView("_Details", model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            // bool result = this.usersService.Delete(id);

            bool result = false;
            
            if (result)
            {
                this.ViewData["SuccessMessage"] = "User successfully dleted.";
            }
            else
            {
                this.ViewData["ErrorMessage"] = "Cannot delete this user.";
            }
            
            return this.RedirectToIndex();
        }

        private IActionResult RedirectToIndex()
        {
            var users = this.usersService.GetAllAdmin();
            return this.PartialView("_IndexPartial", users);
        }
    }
}

ShareDrive/ShareDrive/Controllers/CarController.cs
namespace ShareDrive.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using ShareDrive.Exceptions.Car;
    using ShareDrive.Infrastructure.Filters;
    using ShareDrive.Models;
    using ShareDrive.Services.Contracts;
    using ShareDrive.ViewModels.CarViewModels;

    public class CarController : Controller
    {
        [HttpGet]
        public IActionResult Index([FromServices] ICarsService carsService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            var cars = carsService.GetAllCarsIndex(userId);
            return this.View("Index", cars);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult IndexPartial([FromServices] ICarsService carsService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            var cars = carsService.GetAllCarsIndex(userId);
            return this.View("_IndexPartial", cars);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Create()
        {
            return this.PartialView("_CreateModal");
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Create(CarCreateViewModel model, 
            [FromServices] ICarsService carsService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    int userId = int.Parse(userManager.GetUserId(User));
                    await carsService.Create(model, userId);
                    return Json(new { success = "true", message = "Car successfully created." });
                }
                catch(CarCreateException ex)
                {
                    return Json(new { success = "false", message = ex.Message });
                }
            }

            return this.PartialView("_CreateModal", model);
        }
        
        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Edit(int id, [FromServices] ICarsService carsService)
        {
            CarEditViewModel model = carsService.GetEditViewModel(id);

            if (model != null)
            {
                return this.PartialView("_EditModal", model);
            }

            return this.RedirectToAction("Error", "Home");
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Edit(int id, CarEditViewModel model,
            [FromServices] ICarsService carsService)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    await carsService.Edit(id, model);
                    return Json(new { success = "true", message = "Car successfully edited." });
                }
                catch (CarEditException ex)
                {
                    return Json(new { success = "false", message = ex.Message });
                }
            }

            return this.PartialView("_EditModal", model);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Delete(int id, [FromServices] ICarsService carsService)
        {
            CarDeleteViewModel model = carsService.GetDeleteViewModel(id);

            if (model != null)
            {
                return this.PartialView("_DeleteConfirmation", model);
            }

            return this.RedirectToAction("Error", "Home");
        }

        [HttpPost]
        [AjaxOnly]
        public IActionResult DeleteConfirm(int id, [FromServices] ICarsService carsService)
        {
            try
            {
                bool result = carsService.Delete(id);

                if (result)
                {
                    return Json(new { success = "true", message = "Car successfully deleted." });
                }
                else
                {
                    return this.RedirectToAction("Error", "Home");
                }
            }
            catch (CarDeleteException ex)
            {
                return Json(new { success = "false", message = ex.Message });
            }
        }
    }
}

ShareDrive/ShareDrive/Controllers/DriveController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ShareDrive.ViewModels.Drive;
using Microsoft.AspNetCore.Http;
using ShareDrive.Helpers;
using ShareDrive.Services.Contracts;
using ShareDrive.Infrastructure.Filters;
using Microsoft.AspNetCore.Identity;
using ShareDrive.Models;
using System.Threading.Tasks;

namespace ShareDrive.Controllers
{
    public class DriveController : Controller
    {
        private int userId;

        public DriveController(IHttpContextAccessor contextAccessor)
        {
            this.userId = IdentityHelper.GetUserId(contextAccessor);
        }
        
        [HttpGet]
        public IActionResult Index([FromServices] IDrivesService drivesService)
        {
            return this.RedirectToIndex(drivesService);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult IndexPartial([FromServices] IDrivesService drivesService)
        {
            return this.RedirectToIndexPartial(drivesService);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Create([FromServices] IDriveHelperService driveCarsHelperService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            DriveCreateEditViewModel model = driveCarsHelperService.GetCreateViewModel(userId);
            return this.PartialView("_CreatePartial", model);
        }


        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Create(DriveCreateEditViewModel model, 
            [FromServices] IDriveHelperService driveHelperService, 
            [FromServices] UserManager<ApplicationUser> userManager, 
            [FromServices] IDrivesService drivesService, 
            [FromServices] ICarsService carsService)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            if (this.ModelState.IsValid)
            {
                try
                {
                    await driveHelperService.ProcessCreateDriveAsync(model, userId);
                    return Json(new { success = "true", message = "Drive successfully created." });
                }
                catch (Exception ex)
                {                    
                    return Json(new { success = "false", message = "An error has occured." });
                }               
            }
            
            var cars = carsService.GetSelectionListByDriver(userId);
            model.Cars = cars;
            return this.PartialView("_CreatePartial", model);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Edit(int id, [FromServices] IDriveHelperService driveCarsHelperService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            DriveCreateEditViewModel model = driveCarsHelperService.GetEditViewModel(id, userId);

            return this.PartialView("_EditPartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Edit(int id, 
            DriveCreateEditViewModel model, 
            [FromServices] IDriveHelperService driveHelperService, 
            [FromServices] IDrivesService drivesService,
            [FromServices] UserManager<ApplicationUser> userManager,
            [FromServices] ICarsService carsService)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            if (this.ModelState.IsValid)
            {
                try
                {
                    await driveHelperService.ProcessEditDriveAsync(model, id);
                    return Json(new { success = "true", message = "Drive successfully edited." });
                }
                catch(Exception ex)
                {
                    return Json(new { success = "false", message = "An error has occured." });
                }
            }

            var cars = carsService.GetSelectionListByDriver(userId);
            model.Cars = cars;
            return this.PartialView("_EditPartial", model);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Delete(int id, [FromServices] IDrivesService drivesService)
        {
            DriveDeleteViewModel model = drivesService.GetDeleteModelById(id);
            return this.PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public IActionResult DeleteConfirm(int id, [FromServices] IDrivesService drivesService)
        {
            try
            {
                drivesService.Delete(id);
                return Json(new { success = "true", message = "Drive successfully deleted." });
            }
            catch(Exception ex)
            {
                return Json(new { success = "false", message = "An error has occured." });
            }
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Details(int id, [FromServices] IDrivesService drivesService)
        {
            DriveCollectionsViewModel model = drivesService.GetDetailsModel(id, this.userId);
            return this.PartialView("_DetailsPartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public JsonResult Reserve(int id, [FromServices] IDrivesService drivesService)
        {
            KeyValuePair<bool, string> result = drivesService.ReserveSeat(id, this.userId);
            return Json(new { result = result.Key, message = result.Value });
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public JsonResult Cancel(int id, [FromServices] IDrivesService drivesService)
        {
            KeyValuePair<bool, string> result = drivesService.CancelReservation(id, this.userId);
            return Json(new { result = result.Key, message = result.Value });
        }

        //[Authorize]
        //[AjaxOnly]
        //public IActionResult IndexFilter(string sort, string from, string to, string date, [FromServices] IDrivesService drivesService)
        //{
        //    var drives = drivesService.GetAll(sort, from, to, date);
        //    return this.PartialView("_Index", drives);
        //}        

        private IActionResult RedirectToIndexPartial(IDrivesService drivesService)
        {
            IEnumerable<DriveIndexViewModel> drives = drivesService.GetAll();
            return this.PartialView("_IndexPartial", drives);
        }

        private IActionResult RedirectToIndex(IDrivesService drivesService)
        {
            IEnumerable<DriveIndexViewModel> drives = drivesService.GetAll();
            return this.View("Index", drives);
        }

    }
}

ShareDrive/ShareDrive/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ShareDrive.Models

@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShareDrive</title>

    <environment include="Development">

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/panel.css" />
        <link rel="stylesheet" href="~/css/car-index.css" />
        <link rel="stylesheet" href="~/css/drive-details.css" />
        <link rel="stylesheet" href="~/css/table.css" />
        <link rel="stylesheet" href="~/css/font-awesome-4.7.0/css/font-awesome.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ShareDrive</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_NavigationPartial")
                

                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @Html.Partial("_NotificationSuccessPartial")
        @Html.Partial("_NotificationErrorPartial")

        

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ShareDrive</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>

        <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>


    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>


        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>

ShareDrive/ShareDrive/Views/Shared/_NavigationPartial.cshtml
@using ShareDrive.Infrastructure

<ul class="nav navbar-nav">
    @if (User.IsInRole(GlobalConstants.RoleUser))
    {

        <li><a asp-area="" asp-controller="Drive" asp-action="Index">Drives</a></li>
        <li><a asp-area="" asp-controller="Car" asp-action="Index">Cars</a></li>

    }
    else if (User.IsInRole(GlobalConstants.RoleAdministrator))
    {
        <li><a asp-area="Admin" asp-controller="Drives" asp-action="Index">Drives</a></li>
        <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
        <li><a asp-area="Admin" asp-controller="Cars" asp-action="Index">Cars</a></li>
    }
    else
    {
        <li><a asp-area="" asp-controller="Drive" asp-action="Index">Drives</a></li>
    }
</ul>

ShareDrive/ShareDrive/Views/Shared/_NotificationErrorPartial.cshtml
@if (ViewData["ErrorMessage"] != null)
{
    <div id="error" class="col-md-12">
        <div style="margin-top: 10px" class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @ViewData["ErrorMessage"]
        </div>
    </div>
}

ShareDrive/ShareDrive/Views/Shared/_NotificationSuccessPartial.cshtml
@if (ViewData["SuccessMessage"] != null)
{
    <div class="col-md-12">
        <div style="margin-top: 10px" class="alert alert-success alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @ViewData["SuccessMessage"]
        </div>
    </div>
}