ShareDrive/ShareDrive/Areas/Admin/Controllers/DrivesController.cs
using Microsoft.AspNetCore.Mvc;
using ShareDrive.Services.Contracts;
using ShareDrive.ViewModels.Admin.Drive;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShareDrive.Areas.Admin.Controllers
{
    public class DrivesController : BaseController
    {
        private readonly IDrivesService drivesService;

        public DrivesController(IDrivesService drivesService)
        {
            this.drivesService = drivesService;
        }

        public IActionResult Index()
        {
            IEnumerable<DriveAdminIndexViewModel> drives = this.drivesService.GetAllAdmin();
            return this.View("DrivesIndex", drives);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            DriveAdminDetailsViewModel model = this.drivesService.GetDetailsAdminModel(id);
            return this.PartialView("_DriveDetails", model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            //bool result = this.drivesService.Delete(id);

            bool result = true;

            if(result)
            {
                ViewData["SuccessMessage"] = "Drive deleted successfully";
            }
            else
            {
                ViewData["ErrorMessage"] = "Cannot delete this drive.WS";
            }
            

            IEnumerable<DriveAdminIndexViewModel> drives = this.drivesService.GetAllAdmin();
            return this.PartialView("_DrivesIndexPartial", drives);
        }
    }
}

ShareDrive/ShareDrive/Controllers/DriveController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ShareDrive.ViewModels.Drive;
using Microsoft.AspNetCore.Http;
using ShareDrive.Helpers;
using ShareDrive.Services.Contracts;
using ShareDrive.Infrastructure.Filters;
using Microsoft.AspNetCore.Identity;
using ShareDrive.Models;
using System.Threading.Tasks;

namespace ShareDrive.Controllers
{
    public class DriveController : Controller
    {
        private int userId;

        public DriveController(IHttpContextAccessor contextAccessor)
        {
            this.userId = IdentityHelper.GetUserId(contextAccessor);
        }
        
        [HttpGet]
        public IActionResult Index([FromServices] IDrivesService drivesService)
        {
            return this.RedirectToIndex(drivesService);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult IndexPartial([FromServices] IDrivesService drivesService)
        {
            return this.RedirectToIndexPartial(drivesService);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Create([FromServices] IDriveHelperService driveCarsHelperService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            DriveCreateEditViewModel model = driveCarsHelperService.GetCreateViewModel(userId);
            return this.PartialView("_CreatePartial", model);
        }


        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Create(DriveCreateEditViewModel model, 
            [FromServices] IDriveHelperService driveHelperService, 
            [FromServices] UserManager<ApplicationUser> userManager, 
            [FromServices] IDrivesService drivesService, 
            [FromServices] ICarsService carsService)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            if (this.ModelState.IsValid)
            {
                try
                {
                    await driveHelperService.ProcessCreateDriveAsync(model, userId);
                    return Json(new { success = "true", message = "Drive successfully created." });
                }
                catch (Exception ex)
                {                    
                    return Json(new { success = "false", message = "An error has occured." });
                }               
            }
            
            var cars = carsService.GetSelectionListByDriver(userId);
            model.Cars = cars;
            return this.PartialView("_CreatePartial", model);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Edit(int id, [FromServices] IDriveHelperService driveCarsHelperService,
            [FromServices] UserManager<ApplicationUser> userManager)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            DriveCreateEditViewModel model = driveCarsHelperService.GetEditViewModel(id, userId);

            return this.PartialView("_EditPartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public async Task<IActionResult> Edit(int id, 
            DriveCreateEditViewModel model, 
            [FromServices] IDriveHelperService driveHelperService, 
            [FromServices] IDrivesService drivesService,
            [FromServices] UserManager<ApplicationUser> userManager,
            [FromServices] ICarsService carsService)
        {
            int userId = int.Parse(userManager.GetUserId(User));
            if (this.ModelState.IsValid)
            {
                try
                {
                    await driveHelperService.ProcessEditDriveAsync(model, id);
                    return Json(new { success = "true", message = "Drive successfully edited." });
                }
                catch(Exception ex)
                {
                    return Json(new { success = "false", message = "An error has occured." });
                }
            }

            var cars = carsService.GetSelectionListByDriver(userId);
            model.Cars = cars;
            return this.PartialView("_EditPartial", model);
        }

        [HttpGet]
        [Authorize]
        [AjaxOnly]
        public IActionResult Delete(int id, [FromServices] IDrivesService drivesService)
        {
            DriveDeleteViewModel model = drivesService.GetDeleteModelById(id);
            return this.PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public IActionResult DeleteConfirm(int id, [FromServices] IDrivesService drivesService)
        {
            try
            {
                drivesService.Delete(id);
                return Json(new { success = "true", message = "Drive successfully deleted." });
            }
            catch(Exception ex)
            {
                return Json(new { success = "false", message = "An error has occured." });
            }
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Details(int id, [FromServices] IDrivesService drivesService)
        {
            DriveCollectionsViewModel model = drivesService.GetDetailsModel(id, this.userId);
            return this.PartialView("_DetailsPartial", model);
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public JsonResult Reserve(int id, [FromServices] IDrivesService drivesService)
        {
            KeyValuePair<bool, string> result = drivesService.ReserveSeat(id, this.userId);
            return Json(new { result = result.Key, message = result.Value });
        }

        [HttpPost]
        [Authorize]
        [AjaxOnly]
        public JsonResult Cancel(int id, [FromServices] IDrivesService drivesService)
        {
            KeyValuePair<bool, string> result = drivesService.CancelReservation(id, this.userId);
            return Json(new { result = result.Key, message = result.Value });
        }

        //[Authorize]
        //[AjaxOnly]
        //public IActionResult IndexFilter(string sort, string from, string to, string date, [FromServices] IDrivesService drivesService)
        //{
        //    var drives = drivesService.GetAll(sort, from, to, date);
        //    return this.PartialView("_Index", drives);
        //}        

        private IActionResult RedirectToIndexPartial(IDrivesService drivesService)
        {
            IEnumerable<DriveIndexViewModel> drives = drivesService.GetAll();
            return this.PartialView("_IndexPartial", drives);
        }

        private IActionResult RedirectToIndex(IDrivesService drivesService)
        {
            IEnumerable<DriveIndexViewModel> drives = drivesService.GetAll();
            return this.View("Index", drives);
        }

    }
}

ShareDrive/ShareDrive/Areas/Admin/Views/Drives/DrivesIndex.cshtml
@model IEnumerable<ShareDrive.ViewModels.Admin.Drive.IndexViewModel>

<h2>Drives</h2>

<div id="modal-container" class="modal fade hidden-print" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

<div id="data-container" class="col-md-12">
    @Html.Partial("_DrivesIndexPartial", Model);
</div>

ShareDrive/ShareDrive/Areas/Admin/Views/Drives/_DriveDetails.cshtml
@model ShareDrive.ViewModels.Admin.Drive.DetailsViewModel

<div id="target">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Share Your Drive</h4>
    </div>

    <div class="modal-body">
        <div class="panel-body">
            <div class="col-md-4">
                <div>
                    <label asp-for="@Model.From"></label>
                    <span>@Model.From</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.To"></label>
                    <span>@Model.To</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="Date"></label>
                    <span>@Model.Date</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.Time"></label>
                    <span>@Model.Time</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.LocationToPick"></label>
                    <span>@Model.LocationToPick</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.LocationToArrive"></label>
                    <span>@Model.LocationToArrive</span>
                    <hr class="hr-details" />
                </div>
            </div>

            <div class="col-md-4">
                <div>
                    <label asp-for="@Model.DriverName"></label>
                    <span>@Model.DriverName</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.CarIdentifier"></label>
                    <span>@Model.CarIdentifier</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.DeclaredSeats"></label>
                    <span>@Model.DeclaredSeats</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.PassengersCount"></label>
                    <span>@Model.PassengersCount</span>
                    <hr class="hr-details" />
                </div>

                <div>
                    <label asp-for="@Model.AvailableSeats"></label>
                    <span>@Model.AvailableSeats</span>
                    <hr class="hr-details" />
                </div>
            </div>

            <div class="col-md-4">
                <label asp-for="@Model.PassengersNames"></label>
                @foreach (var passenger in Model.PassengersNames)
                {
                    <div>
                        @passenger
                    </div>
                }
                <hr class="hr-details" />
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <a id="delete" asp-area="Admin" asp-controller="Drives" asp-action="Delete" asp-route-id="@Model.Id"
           class="btn btn-danger">Delete</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    </div>
</div>

<script>
    $(function () {
        $('#modal-container').on('hidden.bs.modal', function () {
            // remove the bs.modal data attribute from it
            $(this).removeData('bs.modal');
            // and empty the modal-content element
            $('#modal-container .modal-content').empty();
        });

        $('#delete').click(function (event) {
            event.preventDefault();
            let url = $(this).attr('href');

            $.post(url, function (data) {
                debugger
                $('#data-container').empty();
                $('#data-container').html(data);
                $('#modal-container').modal('toggle');
            })
        })
    })
</script>

ShareDrive/ShareDrive/Areas/Admin/Views/Drives/_DrivesIndexPartial.cshtml
@model IEnumerable<ShareDrive.ViewModels.Admin.Drive.IndexViewModel>

@Html.Partial("_NotificationSuccessPartial")
@Html.Partial("_NotificationErrorPartial")

<table class="responstable">
    <tr>
        <th>Id</th>
        <th>From</th>
        <th>To</th>
        <th>Date</th>
        <th></th>
    </tr>

    @foreach (var item in @Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.From</td>
            <td>@item.To</td>
            <td>@item.Date</td>
            <td>
                <a asp-area="Admin" asp-action="Details" asp-controller="Drives" asp-route-id="@item.Id"
                   data-target="#modal-container" tabindex="-1"
                   data-toggle="modal" class="btn btn-info">View</a>
            </td>
        </tr>
    }
</table>